# Generated by Django 4.1.5 on 2023-01-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('input_format', models.CharField(blank=True, max_length=255)),
                ('output_format', models.CharField(blank=True, max_length=255)),
                ('video', models.FileField(upload_to='video/')),
                ('complete', models.BooleanField()),
                ('status', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
