# Generated by Django 4.1.5 on 2023-01-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
