# Generated by Django 4.1.5 on 2023-02-01 11:32

from django.db import migrations, models
import video_converter.models


class Migration(migrations.Migration):

    dependencies = [
        ('video_converter', '0002_alter_video_complete_alter_video_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='input_format',
            new_name='cookie',
        ),
        migrations.AlterField(
            model_name='video',
            name='output_format',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to=video_converter.models.rename_file),
        ),
    ]
