# Generated by Django 4.1.5 on 2023-02-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_converter', '0003_rename_input_format_video_cookie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='output_name',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
