# Generated by Django 4.1.5 on 2023-02-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_converter', '0005_alter_video_output_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='cookie',
            new_name='job_id',
        ),
        migrations.AlterField(
            model_name='video',
            name='complete',
            field=models.IntegerField(default=0),
        ),
    ]
